# Generated by Django 3.0.4 on 2020-04-20 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Prioritys',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название задачи')),
                ('content', models.TextField(verbose_name='текст задачи')),
                ('created', models.DateTimeField(verbose_name='дата создания')),
                ('due_date', models.DateField(default='2020-04-20')),
                ('state', models.BooleanField(default=True)),
                ('executor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Исполнитель')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к закрытию задачи')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='tasks.Category')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='tasks.Priority')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
